application: giewiki
version: 2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /empty.html
  static_files: empty.html
  upload: empty.html

- url: /index.xml
  script: index.py

- url: /.*
  script: iewiki.py
