application: giewiki
version: 11
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /scripts
  static_dir: scripts

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /index.xml
  script: index.py
  
- url: /config.js
  script: config.py

- url: /dynamic/iewiki-xsl
  script: dynamic-xsl.py

- url: /dynamic/js/.*
  script: dynamic-xsl.py

- url: /.*
  script: iewiki.py
